import { useState } from "react";
import api from "../api/client";

const LEVEL_NAMES = {
  1: "Nudge",
  2: "Concept",
  3: "Direction",
  4: "Algorithm",
  5: "Pseudocode",
  6: "Implementation"
};
const NAME = { qwen: "Qwen", gemini: "Gemini", grok: "Grok" };

function ProviderChip({ info }) {
  if (!info) return null;
  return info.fallback ? (
    <span className="text-[11px] font-mono text-amber-700 border border-amber-300 bg-amber-50 px-2 py-0.5 rounded-sm">
      ↩ served by {NAME[info.used]} · {info.fallbackReason}
    </span>
  ) : (
    <span className="text-[11px] font-mono text-muted border border-line px-2 py-0.5 rounded-sm">
      via {NAME[info.used]} · {info.model} · {info.latencyMs} ms
    </span>
  );
}

export default function Workspace({ provider, onRunStart, onRunResult, onProblemFinalized }) {
  const [problemText, setProblemText] = useState("");
  const [code, setCode] = useState("");
  const [analysis, setAnalysis] = useState(null); // { ...analysis, provider }
  const [hints, setHints] = useState([]); // { level, text, provider }
  const [loading, setLoading] = useState(null); // "analyze" | "hint" | "submit" | null
  const [error, setError] = useState(null);
  const [resolved, setResolved] = useState(false);

  const currentLevel = hints.length ? Math.max(...hints.map((h) => h.level)) : 0;
  const lastProvider = hints.length ? hints[hints.length - 1].provider : analysis?.provider;

  async function handleAnalyze() {
    if (!problemText.trim()) {
      setError("Paste a problem statement first.");
      return;
    }
    setError(null);
    setLoading("analyze");
    onRunStart?.("analyze");
    try {
      const res = await api.analyze(problemText, code, provider);
      setAnalysis({ ...res.analysis, provider: res.provider });
      onRunResult?.({ kind: "analyze", trace: res.trace, level: res.currentLevel });
    } catch (e) {
      setError(e.message);
      onRunResult?.({ kind: "analyze", trace: null, level: currentLevel });
    } finally {
      setLoading(null);
    }
  }

  async function handleHint() {
    if (!problemText.trim()) {
      setError("Paste a problem statement first.");
      return;
    }
    setError(null);
    setLoading("hint");
    onRunStart?.("hint");
    try {
      const res = await api.getHint(problemText, code, provider);
      setHints((prev) => [...prev, { level: res.level, text: res.text, provider: res.provider }]);
      onRunResult?.({ kind: "hint", trace: res.trace, level: res.level });
    } catch (e) {
      setError(e.message);
      onRunResult?.({ kind: "hint", trace: null, level: currentLevel });
    } finally {
      setLoading(null);
    }
  }

  async function handleSubmit(solved) {
    setError(null);
    setLoading("submit");
    try {
      const res = await api.submitAttempt(problemText, solved, false);
      if (res.finalized) {
        setResolved(true);
        onProblemFinalized?.();
      }
    } catch (e) {
      setError(e.message);
    } finally {
      setLoading(null);
    }
  }

  function resetWorkspace() {
    setProblemText("");
    setCode("");
    setAnalysis(null);
    setHints([]);
    setResolved(false);
    setError(null);
    onRunResult?.({ kind: null, trace: null, level: 0 });
  }

  return (
    <div className="card space-y-4">
      <div className="flex items-center justify-between">
        <div className="card-title mb-0">Coding Workspace</div>
        {currentLevel > 0 && (
          <span className="level-badge">
            L{currentLevel} — {LEVEL_NAMES[currentLevel]}
          </span>
        )}
      </div>

      <div>
        <label className="text-xs text-muted block mb-1">Problem statement</label>
        <textarea
          className="input-field h-24 resize-none font-sans"
          placeholder="Paste the coding problem here…"
          value={problemText}
          onChange={(e) => setProblemText(e.target.value)}
          disabled={resolved}
        />
      </div>

      <div>
        <label className="text-xs text-muted block mb-1">Your code</label>
        <textarea
          className="input-field h-40 resize-none font-mono"
          placeholder="Paste your current attempt…"
          value={code}
          onChange={(e) => setCode(e.target.value)}
          disabled={resolved}
        />
      </div>

      {error && <p className="text-sm text-red-700 bg-red-50 border border-red-200 px-3 py-2 rounded-sm">{error}</p>}

      {lastProvider?.fallback && (
        <p className="text-sm text-amber-800 bg-amber-50 border border-amber-200 px-3 py-2 rounded-sm">
          <strong>{NAME[lastProvider.requested]}</strong> was unavailable ({lastProvider.fallbackReason}). The latest response was generated by{" "}
          <strong>Qwen</strong> instead.
        </p>
      )}

      <div className="flex flex-wrap gap-2">
        <button className="btn-primary" onClick={handleAnalyze} disabled={loading !== null || resolved}>
          {loading === "analyze" ? "Analyzing…" : "Analyze"}
        </button>
        <button className="btn-secondary" onClick={handleHint} disabled={loading !== null || resolved}>
          {loading === "hint" ? "Thinking…" : "Get Next Hint"}
        </button>
        <button className="btn-secondary" onClick={() => handleSubmit(true)} disabled={loading !== null || resolved}>
          Submit Attempt (Solved)
        </button>
        <button className="btn-secondary" onClick={() => handleSubmit(false)} disabled={loading !== null || resolved}>
          Submit Attempt (Not Yet)
        </button>
      </div>

      {analysis && (
        <div className="border border-line rounded-sm p-3 bg-accentSoft text-sm">
          <div className="flex items-center justify-between gap-2 flex-wrap mb-1">
            <p className="text-xs text-muted uppercase tracking-wide">Mentor Diagnostic</p>
            <ProviderChip info={analysis.provider} />
          </div>
          <p>
            <span className="text-muted">Status:</span> {analysis.status} &nbsp;
            <span className="text-muted">Issue:</span> {analysis.issueType}
          </p>
          <p className="mt-1">{analysis.summary}</p>
        </div>
      )}

      {hints.length > 0 && (
        <div className="space-y-3">
          <p className="text-xs text-muted uppercase tracking-wide">AI Mentor Response</p>
          {hints.map((h, i) => (
            <div key={i} className="border border-line rounded-sm p-3">
              <div className="flex items-center justify-between gap-2 flex-wrap mb-2">
                <p className="level-badge">
                  L{h.level} — {LEVEL_NAMES[h.level]}
                </p>
                <ProviderChip info={h.provider} />
              </div>
              <p className="text-sm whitespace-pre-wrap">{h.text}</p>
            </div>
          ))}
        </div>
      )}

      {resolved && (
        <div className="border border-line rounded-sm p-3 bg-accentSoft flex items-center justify-between">
          <p className="text-sm">Problem recorded to history.</p>
          <button className="btn-secondary" onClick={resetWorkspace}>
            Start Next Problem
          </button>
        </div>
      )}
    </div>
  );
}
